### ISSUE TITLE
Unable to successfully add SSH

### ISSUE THREAD

**Issue by karneaud** [debitoor/ssh-private-key-buildpack#8]
Trying to use your package to add bitbucket to the list of known host and get the error

> Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts. 
> remote: Permission denied (publicly).

**Comment by rickschoo** [comment]
Yeah, here as well. Could use some help with this too.

**Comment by karneaud** [comment]
@rickschoo 

I had to manually add this using the code for this package in my build project. You should too as this project maybe abandoned
